global:
  pattern: xray
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  # XRay configuration for service-point config map
  # Found in charts/datacenter/xraylab/templates
  #   datacenter:
  #     clustername: <cluster-name>
  #     domain: <domain>

  datacenter:
    region: us-west1 #us-east-1
    clustername: med-hub-gcp #OpenShift clusterName
    domain: edge.css-qe.com #blueprints.rhecoeng.com

  xraylab:
    namespace: "xraylab-1"

    s3:
      # Values for S3 bucket access
      # Replace <region> with AWS region where S3 bucket was created
      # Replace <cluster-name> and <domain> with your OpenShift cluster values
      # bucketSource: "https://s3.<region>.amazonaws.com/com.redhat.claudiol.xray-source"
      bucketSource: "https://s3.us-west-2.amazonaws.com/ml-md-bucket" #"https://s3.<region>.amazonaws.com/com.redhat.claudiol.xray-source"
      # Bucket base name used for xray images
      bucketBaseName: "xraylab-1"

main:
  clusterGroupName: datacenter
