global:
  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

clusterGroup:
  name: datacenter

  proposedOptions:
    manageGitops: True
    isHubCluster: True

  namespaces:
  - open-cluster-management
  - openshift-serverless
  - opendatahub
  - openshift-storage
  - xraylab-1
  - knative-serving
  - staging
  - vault
  - medical-diagnosis-datacenter

  operatorgroupExcludes:
    - operatorhub
    - knative-kafka

  subscriptions:
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3
    csv: advanced-cluster-management.v2.3.2

  - name: amq-streams
    namespace: xraylab-1 
    channel: stable
    csv: amqstreams.v1.7.1

  - name: grafana-operator
    namespace: xraylab-1 
    channel: v4
    source: community-operators
    csv: grafana-operator.v3.10.3

  - name: odf-operator
    namespace: openshift-storage
    channel: stable-4.9
    csv: odf-operator.v4.9.1

  - name: serverless-operator
    channel: stable
    csv: serverless-operator.v1.7.2

  - name: opendatahub-operator
    source: community-operators
    csv: opendatahub-operator.v1.1.0


  projects:
  - datacenter
 
  applications:
  - name: acm
    namespace: open-cluster-management
    project: datacenter
    path: common/acm

  - name: odh
    namespace: opendatahub
    project: datacenter
    path: charts/datacenter/opendatahub

  - name: cephobjectstore
    namespace: openshift-storage
    project: datacenter
    path: charts/datacenter/cephobjectstore

  - name: knative
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/knative

  - name: demo
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/demo

  - name: user
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/user
    
  - name: kafka
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/kafka

  - name: kafkasource
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/kafkasource

  - name:  grafana
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/grafana

  - name:  imageserver
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/image-server

  - name:  imagegenerator
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/image-generator
    
  - name: xraydb
    namespace: xraylab-1
    project: datacenter
    path: charts/datacenter/xraylab/xraydb
  
  - name: hashivault
    namespace: vault
    project: datacenter
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.17.1
    overrides:
    - name: build.enabled
      value: "false"
      forceString: true
    - name: deploy.route.tls.enabled
      value: "true"
      forceString: true
    - name: global.openshift
      value: "true"
      forceString: true
    - name: server.dev.enabled
      value: "true"
      forceString: true

#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam 
#  
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#  
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

  managedSites:
  - name: factory
    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
    targetRevision: main
    path: applications/factory
    helmOverrides:
    - name: site.isHubCluster
      value: false
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

